import React from "react";
import QueryProvider from "@/components/custom/query-provider";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {cn} from "@/lib/utils";
import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Jira Clone | Fatih AK",
    description: "Generated by Fatih AK",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn(inter.className, "antialiased min-h-screen")}
        >
        <QueryProvider>
            {children}
        </QueryProvider>
        </body>
        </html>
    );
}
